### ISSUE TITLE
NootedRed

### ISSUE THREAD

**Issue by jorgeiba97** [sleepppwalker/opencore-ryzentosh-huawei-matebook-13-amd#1]
Hi, thank you so much for the EFI, it works like a charm for install Mac OS Ventura. Te problem is how to fix IGPU, i have installed the Nootred kext but is not working, can you tell me how you did to fix IGPU?

Thanks in advance

**Comment by sleepppwalker** [comment]
Hi, need to add NootedRed.kext in folder where other kext and enable in config.plist, after that disable WhateverGreen.kext with uninstall from folder!
