### ISSUE TITLE
Matebook 13 amd hackintosh

### ISSUE THREAD

**Issue by 0mew** [sleepppwalker/opencore-ryzentosh-huawei-matebook-13-amd#2]
Would this EFI work for my system?

Matebook 13
ryzen 7 3700u
amd radeon vega 10
16gb ram
Realtek 8822CE

Is this EFI file suitable for Sonoma or Ventura? And can I use it for my computer without making any changes? Additionally, could you share a resource on how to install it?

**Comment by sleepppwalker** [comment]
The beginning - I don't know.
You can go to the Dortanya website and watch on your own equipment.
https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html#prerequisites
Let me also remind you that this EFI is not fully completed, so it needs to be edited in any case.
(I don’t have time right now, maybe I’ll do it later)
